//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OceanParadiseeHotelEntities : DbContext
    {
        public OceanParadiseeHotelEntities()
            : base("name=OceanParadiseeHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminPanel> AdminPanels { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<GUEST_TABLE> GUEST_TABLE { get; set; }
        public virtual DbSet<PAYMENT> PAYMENTs { get; set; }
        public virtual DbSet<Room_image> Room_image { get; set; }
        public virtual DbSet<room_tab> room_tab { get; set; }
    }
}
