//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_image
    {
        public int room_id { get; set; }
        public int adminID { get; set; }
        public string image { get; set; }
    
        public virtual AdminPanel AdminPanel { get; set; }
    }
}
