//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerTable
    {
        public int ManageId { get; set; }
        public string ManageName { get; set; }
        public string Manageddress { get; set; }
        public string ManageContact { get; set; }
    }
}
